### ISSUE TITLE
Tables are not the only objects in the database

### ISSUE THREAD

**Issue by pmatseykanets** [spatie/laravel-migrate-fresh#20]
Although for the majority of simple, in terms of DB schema, projects just a table dropper will suffice, but technically speaking there are other very important objects in the database that can be migrated and should be taken care of:
* sequences - the ones that weren't created as part of `SERIAL` data type and therefore won't be affected by `CASCADE`
* functions
* custom data types and domains

And there is also a situation when one may use multiple schemas in the database for very good and practical reasons i.e. separating staging/processing and factual schemas.

**Comment by freekmurze** [comment]
I'd accept a PR that makes the droppers more robust.
