### ISSUE TITLE
Rename `TableDropper` to `DbObjectDropper`

### ISSUE THREAD

**Issue by pmatseykanets** [spatie/laravel-migrate-fresh#23]
I'd propose to change the interface to something like

```php
namespace Spatie\MigrateFresh\DbObjectDroppers;

interface DbObjectDropper
{
    public function dropAll();
}
```

to better reflect the  reality - tables are not the only database objects that need to be taken care of.

@freekmurze What is your take on it? I can do the PR and probably help with MySQL and SQLite droppers.

**Comment by freekmurze** [comment]
See comments on #22
