### ISSUE TITLE
Dangerous scope, does not support table prefixes

### ISSUE THREAD

**Issue by ivuorinen** [spatie/laravel-migrate-fresh#26]
First of all, thank you for your awesome contributions.

My concern is that running this inside shared Homestead drops tables that belong to other projects.

There should be implementation of some safeguards that let's the developer know what tables are about to be dropped and a possibility to bail out before any destructive actions take place.

You are welcome to check out how I implemented it [in our similar command](https://github.com/superhelio/commands/blob/develop/src/Commands/Gozer.php). It's still in development and takes a bit different approach (and hasn't been tested yet).

**Comment by freekmurze** [comment]
Thanks for your suggestion.

I'd like to cater to the proverbial 80% that use a seperate db for each application. I'd accept a PR that makes the current behaviour more clear in the readme.
