### ISSUE TITLE
Incompatible with MySQL Views

### ISSUE THREAD

**Issue by redalpha01** [spatie/laravel-migrate-fresh#27]
Command tries to drop views as tables and it stops the execution of the code.

**Comment by freekmurze** [comment]
I'd accept a PR that fixes this.

As an interim solution you could listen for the `Spatie\MigrateFresh\Events\DroppingTable` event to drop your views manually.

**Comment by redalpha01** [comment]
#28 Made a PR that fixes it for me (MySQL only)

**Comment by freekmurze** [comment]
See #28
