### ISSUE TITLE
[FEATURE] Support for LaravelDoctrine Migrations

### ISSUE THREAD

**Issue by jakub-klapka** [spatie/laravel-migrate-fresh#34]
Hello,
do you think, that adding support for LaravelDoctrine Migrations (http://www.laraveldoctrine.org/docs/1.3/migrations) makes sense for this base package? I see lot of people lately, who are starting to use Doctrine on Laravel (I also understand why) and this might be useful for them.

Technically, it simply means not calling `migrate`, but `doctrine:migrations:migrate`. But there will be need for configuration. I'm thinking standard `migrate-fresh.php` published into `config_path()`, where you would specify usage of Laravel migrations or Doctrine migrations.
Feature detection is not possible, since people can use Doctrine with Laravel migrations and vice versa.

I can make PR for that, if you are interested to have it in your package.

Thanks, Jakub

**Comment by freekmurze** [comment]
Thanks for your suggestion, but not a fan. If you make use of Doctrine in Laravel and want to make use of this package, you could overwrite the registration of the standard `migrate` command in the ioc container by a custom command that 'll execute `doctrine:migrations:migrate`.

**Comment by jakub-klapka** [comment]
Ok, I didn't think of that. Thanks!
