### ISSUE TITLE
Class conflict with Schema

### ISSUE THREAD

**Issue by jonphipps** [spatie/laravel-migrate-fresh#38]
Thanks for this project, it's very helpful.

I unfortunately have a project that contains an un-namespaced class called "Schema" that I'm having to integrate into a Laravel app. I can't alter that class, so in my own migrations I've had to fully qualify the Schema facade. I know this isn't your problem at all, but it would be helpful to me (and perhaps future others in my situation) if you could fully qualify the ```use Schema``` in ```Spatie\MigrateFresh\TableDroppers\Mysql```, like so:

```php
<?php

namespace Spatie\MigrateFresh\TableDroppers;

use DB;
use stdClass;
use Illuminate\Support\Facades\Schema;

class Mysql implements TableDropper
```
If not, no worries... Just close this issue and I'll work with a personal fork.

**Comment by freekmurze** [comment]
Could you PR this?

**Comment by jonphipps** [comment]
Sure can.

**Comment by freekmurze** [comment]
PR has been merged.
