### ISSUE TITLE
Add the --path and --database options as per the original migrate commands

### ISSUE THREAD

**Issue by chrispappas** [spatie/laravel-migrate-fresh#46]
It would be very useful to be able to specify the `--path` and `--database` options for use cases where multiple database connections and migration directories are used.

**Comment by freekmurze** [comment]
I'd accept a PR with tests and an updated readme that adds this to the package.

I'm not going to invest anytime in this myself as this package will soon be abandoned because L5.5 will come with `migrate:fresh` baked in.

**Comment by chrispappas** [comment]
Fair point - when I have some "10%" time I may implement. Thanks for all of your hard work in general.
