### ISSUE TITLE
mysql view table dropper is not yet merged on master src

### ISSUE THREAD

**Issue by jericopulvera** [spatie/laravel-migrate-fresh#47]

**Comment by freekmurze** [comment]
Could you describe in more detail what the problem is?

**Comment by freekmurze** [comment]
Closing this for now. Feel free to reopen to point me to pieces of code that are not in the latest release.

**Comment by jericopulvera** [comment]
I have a view in my database and I use the migrate:fresh command from the latest release.

I get an error that view cannot be dropped.

I use mysql database.

I saw a fix on #28 and it has been merged.

But i Looked at the src on the master branch and the code is not there yet.
