### ISSUE TITLE
error when using fresh command and postgis on postgres

### ISSUE THREAD

**Issue by federicogodan** [spatie/laravel-migrate-fresh#56]
hi, when using the comand i get the error:

```bash
ERROR:  cannot drop table  
   spatial_ref_sys because extension postgis requires it                       
  HINT:  You can drop extension postgis instead.
```

In laravel it was solved excluding the table for the drop command, as show in:
https://github.com/laravel/framework/pull/21778/files
and
https://github.com/laravel/framework/pull/21778

can you add the patch please?

ty

**Comment by freekmurze** [comment]
I'd accept a PR for this.

**Comment by federicogodan** [comment]
hi, i test it and the fix isn't working, same error message is displayed

**Comment by federicogodan** [comment]
@freekmurze @prolonginc excuse me for the insistence but the error persist with the actual fix

**Comment by prolonginc** [comment]
Can you verify that the package has the fix in the vendor folder? Could it be possible that you are loding the pckage from the cache?

**Comment by federicogodan** [comment]
mmm checking the vendor file the fix is there. I re run a composer update and try it on a fresh install but still getting the error. As I see, the filter isn't preventing spatial_ref_sys is for being dropped.

**Comment by freekmurze** [comment]
I'd accept a PR that fixes this.
